// src/app/jobs-board/mockJobs.js
export const mockJobs = [
  {
    id: "web-dev",
    title: "Web Developer",
    company: "Stone",
    stage: "process",
    clientStatus: "BPO",
    isHold: false,
    initial: "ST",
    logoColor: "1d4ed8",
    logoUrl: "https://placehold.co/64x64/1d4ed8/ffffff?text=ST",
    location: "Curitiba, State of Paraná, Brazil",
    salaryMin: 5000,
    salaryMax: 8500,
    status: "ACTIVE",
    employmentType: "Full Time",
  },
  {
    id: "qa-analyst",
    title: "QA Analyst",
    company: "Vtex",
    stage: "process",
    clientStatus: "TEMP",
    isHold: true,
    initial: "VT",
    logoColor: "1d4ed8",
    logoUrl: "https://placehold.co/64x64/1d4ed8/ffffff?text=VT",
    location: "São Paulo, State of São Paulo, Brazil",
    salaryMin: 4200,
    salaryMax: 6800,
    status: "ON_HOLD",
    employmentType: "Part Time",
  },
  {
    id: "devops-eng",
    title: "DevOps Eng.",
    company: "iFood",
    stage: "process",
    clientStatus: "EOR",
    isHold: false,
    initial: "IF",
    logoColor: "1d4ed8",
    logoUrl: "https://placehold.co/64x64/1d4ed8/ffffff?text=IF",
    location: "Remote, Brazil",
    salaryMin: 7000,
    salaryMax: 11000,
    status: "ACTIVE",
    employmentType: "Full Time",
  },
  {
    id: "cs-analyst",
    title: "CS Analyst",
    company: "Loggi",
    stage: "process",
    clientStatus: "BPO",
    isHold: false,
    initial: "LG",
    logoColor: "1d4ed8",
    logoUrl: "https://placehold.co/64x64/1d4ed8/ffffff?text=LG",
    location: "Belo Horizonte, State of Minas Gerais, Brazil",
    salaryMin: 3500,
    salaryMax: 5200,
    status: "ACTIVE",
    employmentType: "Full Time",
  },
  {
    id: "sales-rep",
    title: "Sales Rep.",
    company: "Quinto Andar",
    stage: "process",
    clientStatus: "BID",
    isHold: false,
    initial: "QA",
    logoColor: "1d4ed8",
    logoUrl: "https://placehold.co/64x64/1d4ed8/ffffff?text=QA",
    location: "Curitiba, State of Paraná, Brazil",
    salaryMin: 3000,
    salaryMax: 4500,
    status: "ACTIVE",
    employmentType: "Full Time",
  },
  {
    id: "hr-coordinator",
    title: "HR Coordinator",
    company: "Frontall Internal HQ",
    stage: "new",
    clientStatus: "INTERNAL",
    isHold: false,
    initial: "FI",
    logoColor: "0f766e",
    logoUrl: "https://placehold.co/64x64/0f766e/ffffff?text=FI",
    location: "Curitiba, State of Paraná, Brazil",
    salaryMin: 3800,
    salaryMax: 5000,
    status: "ACTIVE",
    employmentType: "Full Time",
  },
  {
    id: "finance-assistant",
    title: "Finance Assistant",
    company: "Contabilizei",
    stage: "concluded",
    clientStatus: "DIRECT_HIRE",
    isHold: false,
    initial: "CT",
    logoColor: "15803d",
    logoUrl: "https://placehold.co/64x64/15803d/ffffff?text=CT",
    location: "São Paulo, State of São Paulo, Brazil",
    salaryMin: 3200,
    salaryMax: 4200,
    status: "INACTIVE",
    employmentType: "Part Time",
  },
];