// src/app/jobs-board/mockJobs.js
export const mockJobs = [
  {
    id: "web-dev",
    title: "Web Developer",
    company: "Nimbus Technology",
    clientId: "nimbus-technology",
    stage: "process",
    clientStatus: "BPO",
    isHold: false,
    initial: "NT",
    logoColor: "0c4a6e",
    logoUrl: "https://placehold.co/64x64/0c4a6e/ffffff?text=NT",
    city: "Curitiba",
    state: "Paraná",
    country: "Brazil",
    salaryMin: 5000,
    salaryMax: 8500,
    status: "ACTIVE",
    employmentType: "Full Time",
    workType: "Hybrid",
    currency: "BRL",
    frequency: "Monthly",
    openDate: "01/07/2026",
    closeDate: null,
    openings: 3,
    priority: "High",
    dashboardNote:
      "Client asked to speed up process due to an internal deadline, prioritize sourcing this week.",
    isReplacement: false,
    cancelReason: null,
    description:
      "We are looking for a Web Developer to join our engineering team, working on customer-facing dashboards and internal tooling. The ideal candidate has 3+ years of experience with React, solid understanding of REST APIs, and good communication in English. This is a hybrid position based in Curitiba, with 2 days in-office per week.",
  },
  {
    id: "qa-analyst",
    title: "QA Analyst",
    company: "Nimbus Technology",
    clientId: "nimbus-technology",
    stage: "submitted",
    clientStatus: "TEMP",
    isHold: true,
    initial: "NT",
    logoColor: "0c4a6e",
    logoUrl: "https://placehold.co/64x64/0c4a6e/ffffff?text=NT",
    city: "Curitiba",
    state: "Paraná",
    country: "Brazil",
    salaryMin: 4200,
    salaryMax: 6800,
    status: "ON_HOLD",
    employmentType: "Part Time",
    workType: "Remote",
    currency: "BRL",
    frequency: "Monthly",
    openDate: "10/06/2026",
    closeDate: null,
    openings: 1,
    priority: "Standard",
    dashboardNote: "On hold, temporary freeze while client reviews test coverage requirements.",
    isReplacement: false,
    cancelReason: null,
    description:
      "Temporary QA Analyst position to support a 6-month product testing initiative. Responsible for writing and executing test plans, reporting bugs, and working closely with the engineering team to validate fixes before release.",
  },
  {
    id: "devops-eng",
    title: "DevOps Eng.",
    company: "Cedro Foods",
    clientId: "cedro-foods",
    stage: "process",
    clientStatus: "DIRECT_HIRE",
    isHold: false,
    initial: "CF",
    logoColor: "0c4a6e",
    logoUrl: "https://placehold.co/64x64/0c4a6e/ffffff?text=CF",
    city: "São Paulo",
    state: "São Paulo",
    country: "Brazil",
    salaryMin: 7000,
    salaryMax: 11000,
    status: "ACTIVE",
    employmentType: "Full Time",
    workType: "Remote",
    currency: "BRL",
    frequency: "Monthly",
    openDate: "15/05/2026",
    closeDate: null,
    openings: 1,
    priority: "Standard",
    dashboardNote: "",
    isReplacement: false,
    cancelReason: null,
    description:
      "Cedro Foods is looking for a DevOps Engineer to own our CI/CD pipelines and cloud infrastructure. You'll work with AWS, Docker, and Kubernetes to keep our production environment reliable and scalable as we grow.",
  },
  {
    id: "cs-analyst",
    title: "CS Analyst",
    company: "Vetta Health",
    clientId: "vetta-health",
    stage: "process",
    clientStatus: "EOR",
    isHold: false,
    initial: "VH",
    logoColor: "0c4a6e",
    logoUrl: "https://placehold.co/64x64/0c4a6e/ffffff?text=VH",
    city: "Belo Horizonte",
    state: "Minas Gerais",
    country: "Brazil",
    salaryMin: 3500,
    salaryMax: 5200,
    status: "ACTIVE",
    employmentType: "Full Time",
    workType: "In Person",
    currency: "BRL",
    frequency: "Monthly",
    openDate: "01/06/2026",
    closeDate: null,
    openings: 2,
    priority: "High",
    dashboardNote: "Client is a new account, this is our first placement with them — high visibility.",
    isReplacement: false,
    cancelReason: null,
    description:
      "Customer Success Analyst to support Vetta Health's growing client base. You'll be the first point of contact for client questions, onboarding new accounts, and identifying opportunities to improve retention.",
  },
  {
    id: "sales-rep",
    title: "Sales Rep.",
    company: "Cedro Foods",
    clientId: "cedro-foods",
    stage: "concluded",
    clientStatus: "BID",
    isHold: false,
    initial: "CF",
    logoColor: "0c4a6e",
    logoUrl: "https://placehold.co/64x64/0c4a6e/ffffff?text=CF",
    city: "São Paulo",
    state: "São Paulo",
    country: "Brazil",
    salaryMin: 3000,
    salaryMax: 4500,
    status: "ACTIVE",
    employmentType: "Full Time",
    workType: "In Person",
    currency: "BRL",
    frequency: "Monthly",
    openDate: "01/03/2026",
    closeDate: "30/06/2026",
    openings: 1,
    priority: "Standard",
    dashboardNote: "",
    isReplacement: false,
    cancelReason: null,
    description:
      "Outbound Sales Representative role focused on new business development for Cedro Foods' B2B distribution channel. Position has been filled and this vacancy is now closed.",
  },
  {
    id: "hr-coordinator",
    title: "HR Coordinator",
    company: "Frontall Internal HQ",
    clientId: "frontall-internal-hq",
    stage: "new",
    clientStatus: "INTERNAL",
    isHold: false,
    initial: "FI",
    logoColor: "0f766e",
    logoUrl: "https://placehold.co/64x64/0f766e/ffffff?text=FI",
    city: "Curitiba",
    state: "Paraná",
    country: "Brazil",
    salaryMin: 3800,
    salaryMax: 5000,
    status: "ACTIVE",
    employmentType: "Full Time",
    workType: "Hybrid",
    currency: "BRL",
    frequency: "Monthly",
    openDate: "05/08/2026",
    closeDate: null,
    openings: 1,
    priority: "Standard",
    dashboardNote: "",
    isReplacement: false,
    cancelReason: null,
    description:
      "Internal HR Coordinator role to support Frontall's own recruitment and people operations team. Responsibilities include scheduling interviews, onboarding new hires, and maintaining employee records.",
  },
  {
    id: "finance-assistant",
    title: "Finance Assistant",
    company: "Legacy Solutions",
    clientId: "legacy-solutions",
    stage: "concluded",
    clientStatus: "DIRECT_HIRE",
    isHold: false,
    initial: "LS",
    logoColor: "64748b",
    logoUrl: "https://placehold.co/64x64/64748b/ffffff?text=LS",
    city: "Miami",
    state: "Florida",
    country: "United States",
    salaryMin: 3200,
    salaryMax: 4200,
    status: "INACTIVE",
    employmentType: "Part Time",
    workType: "In Person",
    currency: "USD",
    frequency: "Hourly",
    openDate: "01/02/2021",
    closeDate: "10/03/2021",
    openings: 1,
    priority: "Standard",
    dashboardNote: "",
    isReplacement: true,
    cancelReason: "No client response",
    description:
      "Part-time Finance Assistant supporting accounts payable and receivable for Legacy Solutions. This position has been closed.",
  },
];