export const mockClients = [
  {
    id: "nimbus-technology",
    name: "Nimbus Technology",
    sector: "Technology",
    status: "ACTIVES",
    since: "Jan 2024",
    website: "https://nimbustechnology.com",
    city: "Curitiba",
    state: "Paraná",
    country: "Brazil",
    zipcode: "80010-000",
    initials: "NT",
    logoColor: "0c4a6e",
    logoUrl: "https://placehold.co/72x72/0c4a6e/ffffff?text=NT",
    contractTags: ["BPO"],
    firstContactDate: "10/01/2024",
    contractSignedDate: "22/01/2024",
    ceoName: "Marcos Vieira",
    ceoPhone: "+55 41 99888-7766",
    primaryContactName: "Rafael Sousa",
    primaryContactEmail: "rafael@nimbustechnology.com",
  },
  {
    id: "cedro-foods",
    name: "Cedro Foods",
    sector: "Industry",
    status: "PROSPECTION",
    since: "Mar 2023",
    website: "https://cedrofoods.com",
    city: "São Paulo",
    state: "São Paulo",
    country: "Brazil",
    zipcode: "01310-000",
    initials: "CF",
    logoColor: "0c4a6e",
    logoUrl: "https://placehold.co/72x72/0c4a6e/ffffff?text=CF",
    contractTags: ["Direct Hire"],
    firstContactDate: "05/03/2023",
    contractSignedDate: "-",
    ceoName: "Marina Costa",
    ceoPhone: "+55 11 98888-1234",
    primaryContactName: "Bianca Melo",
    primaryContactEmail: "bianca@cedrofoods.com",
  },
  {
    id: "vetta-health",
    name: "Vetta Health",
    sector: "Healthcare",
    status: "BID",
    since: "Jun 2026",
    website: "https://vettahealth.com",
    city: "Belo Horizonte",
    state: "Minas Gerais",
    country: "Brazil",
    zipcode: "30130-000",
    initials: "VH",
    logoColor: "0c4a6e",
    logoUrl: "https://placehold.co/72x72/0c4a6e/ffffff?text=VH",
    contractTags: ["EOR"],
    firstContactDate: "01/06/2026",
    contractSignedDate: "-",
    ceoName: "Renata Alves",
    ceoPhone: "+55 31 97777-4321",
    primaryContactName: "Diego Ramos",
    primaryContactEmail: "diego@vettahealth.com",
  },
  {
    id: "frontall-internal-hq",
    name: "Frontall Internal HQ",
    sector: "HR & Ops",
    status: "ACTIVES",
    since: "Jan 2022",
    website: "https://frontallusa.com",
    city: "Curitiba",
    state: "Paraná",
    country: "Brazil",
    zipcode: "80010-000",
    initials: "FI",
    logoColor: "0f766e",
    logoUrl: "https://placehold.co/72x72/0f766e/ffffff?text=FI",
    contractTags: ["Internal"],
    firstContactDate: "01/01/2022",
    contractSignedDate: "10/01/2022",
    ceoName: "—",
    ceoPhone: "—",
    primaryContactName: "Bryan Santana",
    primaryContactEmail: "bryan@frontallusa.com",
  },
  {
    id: "legacy-solutions",
    name: "Legacy Solutions",
    sector: "Consulting",
    status: "INACTIVES",
    since: "Feb 2021",
    website: "https://legacysolutions.com",
    city: "Miami",
    state: "Florida",
    country: "United States",
    zipcode: "33101",
    initials: "LS",
    logoColor: "64748b",
    logoUrl: "https://placehold.co/72x72/64748b/ffffff?text=LS",
    contractTags: ["Temp"],
    firstContactDate: "01/02/2021",
    contractSignedDate: "15/02/2021",
    ceoName: "John Miller",
    ceoPhone: "+1 305 555-0100",
    primaryContactName: "Lucas Lima",
    primaryContactEmail: "lucas@legacysolutions.com",
  },
];