// src/app/candidates/mockCandidateHistory.js
export const mockCandidateHistory = [
  {
    id: "ch1",
    candidateId: "isabella-monteiro",
    userName: "Bryan Santana",
    userInitials: "BS",
    userColor: "#1e3a8a",
    action: "uploaded a document",
    target: "Signed_Contract_Isabella.pdf",
    timeAgo: "4 hours ago",
    dateTime: "20/08/2026, 10:30 AM",
  },
  {
    id: "ch2",
    candidateId: "isabella-monteiro",
    userName: "Rafael Sousa",
    userInitials: "RS",
    userColor: "#c2410c",
    action: "added an interview",
    target: "Web Developer",
    timeAgo: "6 days ago",
    dateTime: "14/08/2026, 02:15 PM",
  },
  {
    id: "ch3",
    candidateId: "isabella-monteiro",
    userName: "Rafael Sousa",
    userInitials: "RS",
    userColor: "#c2410c",
    action: "added a note",
    target: "Strong technical fit",
    timeAgo: "8 days ago",
    dateTime: "12/08/2026, 09:00 AM",
  },
  {
    id: "ch4",
    candidateId: "isabella-monteiro",
    userName: "Bryan Santana",
    userInitials: "BS",
    userColor: "#1e3a8a",
    action: "logged a follow up",
    target: null,
    timeAgo: "5 days ago",
    dateTime: "15/08/2026, 04:00 PM",
  },
  {
    id: "ch5",
    candidateId: "isabella-monteiro",
    userName: "Bianca Melo",
    userInitials: "BM",
    userColor: "#7c3aed",
    action: "moved to Send to Client stage",
    target: "Web Developer",
    timeAgo: "1 month ago",
    dateTime: "15/07/2026, 11:20 AM",
  },
  {
    id: "ch6",
    candidateId: "isabella-monteiro",
    userName: "Bryan Santana",
    userInitials: "BS",
    userColor: "#1e3a8a",
    action: "created the candidate",
    target: null,
    timeAgo: "3 months ago",
    dateTime: "15/05/2024, 10:15 AM",
  },
];