// src/app/candidates/mockCandidates.js
export const mockCandidates = [
  {
    id: "rodrigo-carreirao",
    firstName: "Rodrigo",
    lastName: "Carreirão",
    gender: "Male",
    city: "Curitiba",
    state: "PR",
    country: "Brazil",
    phone: "+55 (41) 99999-1111",
    email: "rodrigo.c@frontall.com",
    linkedin: "linkedin.com/in/rodrigocarreirao",
    appliedJob: "Product Management Consultant",
    currentPosition: "Product Owner",
    source: "LinkedIn",
    createdBy: "Bryan Santana",
    languages: ["Portuguese", "English"],
    pastPositions: ["Product Owner", "Scrum Master"],
    keywords: ["Agile", "Roadmap", "SaaS"],
    createdDate: "2024-02-10",
    photoUrl: "https://placehold.co/150x150/ea580c/ffffff?text=RC",
    resumeUrl: null,
    tags: ["Applied", "Top Fit"],
    preferredContract: "Full-time",
    workModel: "Remote",
    salaryExpectation: "R$ 9.500 / month",
    skills: ["Agile (Scrum)", "Roadmap Planning", "SaaS", "Product Management"],
  },
  {
    id: "gustavo-hammer",
    firstName: "Gustavo",
    lastName: "Hammer",
    gender: "Male",
    city: "São Paulo",
    state: "SP",
    country: "Brazil",
    phone: "+55 (11) 98888-2222",
    email: "gustavo.h@outlook.com",
    linkedin: "linkedin.com/in/gustavohammer",
    appliedJob: "SaaS IT Engineer",
    currentPosition: "DevOps Engineer",
    source: "LinkedIn",
    createdBy: "Rafael Sousa",
    languages: ["Portuguese", "English", "Spanish"],
    pastPositions: ["Full Stack Developer", "DevOps"],
    keywords: ["AI", "Integrations", "Cloud"],
    createdDate: "2024-05-03",
    photoUrl: "https://placehold.co/150x150/1d4ed8/ffffff?text=GH",
    resumeUrl: null,
    tags: ["Applied", "LinkedIn"],
    preferredContract: "Full-time",
    workModel: "Hybrid (2 days in-office)",
    salaryExpectation: "R$ 11.000 / month",
    skills: ["Node.js", "AWS", "Docker", "CI/CD"],
  },
  {
    id: "diogo-pinto",
    firstName: "Diogo",
    lastName: "Pinto",
    gender: "Male",
    city: "Belo Horizonte",
    state: "MG",
    country: "Brazil",
    phone: "+55 (31) 97777-3333",
    email: "diogo.pinto@dev.io",
    linkedin: "linkedin.com/in/diogopinto",
    appliedJob: "Backend Web Developer",
    currentPosition: "Software Developer",
    source: "Company Website",
    createdBy: "Bianca Melo",
    languages: ["Portuguese", "English"],
    pastPositions: ["Software Developer"],
    keywords: ["Node.js", "MongoDB", "React"],
    createdDate: "2024-06-18",
    photoUrl: "https://placehold.co/150x150/15803d/ffffff?text=DP",
    resumeUrl: null,
    tags: ["Active Search"],
    preferredContract: "Full-time",
    workModel: "Remote",
    salaryExpectation: "R$ 7.800 / month",
    skills: ["Node.js", "MongoDB", "React", "REST APIs"],
  },
  {
    id: "alexandre-valenca",
    firstName: "Alexandre",
    lastName: "Valença",
    gender: "Male",
    city: "Florianópolis",
    state: "SC",
    country: "Brazil",
    phone: "+55 (48) 96666-4444",
    email: "alexandre.v@sistemas.com.br",
    linkedin: "linkedin.com/in/alexandrevalenca",
    appliedJob: "Full Stack Developer",
    currentPosition: "Backend Developer",
    source: "ZipRecruiter",
    createdBy: "Bryan Santana",
    languages: ["Portuguese"],
    pastPositions: ["Backend Developer"],
    keywords: ["TypeScript", "Express", "SQL"],
    createdDate: "2024-07-01",
    photoUrl: "https://placehold.co/150x150/7c3aed/ffffff?text=AV",
    resumeUrl: null,
    tags: ["Applied"],
    preferredContract: "Full-time",
    workModel: "On-site",
    salaryExpectation: "R$ 8.200 / month",
    skills: ["TypeScript", "Express", "PostgreSQL"],
  },
  {
    id: "john-doe",
    firstName: "John",
    lastName: "Doe",
    gender: "Male",
    city: "Miami",
    state: "FL",
    country: "United States",
    phone: "+1 (305) 555-0199",
    email: "john.doe@techrec.com",
    linkedin: "linkedin.com/in/johndoe",
    appliedJob: "Backend Web Developer",
    currentPosition: "Software Engineer",
    source: "LinkedIn",
    createdBy: "Rafael Sousa",
    languages: ["English"],
    pastPositions: ["Software Engineer"],
    keywords: ["Next.js", "MongoDB", "TypeScript"],
    createdDate: "2024-08-12",
    photoUrl: "https://placehold.co/150x150/64748b/ffffff?text=JD",
    resumeUrl: null,
    tags: ["LinkedIn"],
    preferredContract: "Full-time",
    workModel: "Remote",
    salaryExpectation: "US$ 5.200 / month",
    skills: ["Next.js", "MongoDB", "TypeScript"],
  },
  {
    id: "maria-eduarda-f",
    firstName: "Maria",
    lastName: "Eduarda F.",
    gender: "Female",
    city: "Curitiba",
    state: "PR",
    country: "Brazil",
    phone: "+55 (41) 98765-1122",
    email: "maria.eduarda@email.com",
    linkedin: "linkedin.com/in/mariaeduardaf",
    appliedJob: "Social Media & Content Coordinator",
    currentPosition: "Marketing Analyst",
    source: "Company Website",
    createdBy: "Bianca Melo",
    languages: ["Portuguese"],
    pastPositions: ["Analista de marketing"],
    keywords: ["Marketing", "Social Media"],
    createdDate: "2026-07-10",
    photoUrl: "https://placehold.co/150x150/64748b/ffffff?text=ME",
    resumeUrl: null,
    tags: ["Applied"],
    preferredContract: "Full-time",
    workModel: "Hybrid (2 days in-office)",
    salaryExpectation: "R$ 4.200 / month",
    skills: ["Marketing", "Social Media", "Content Creation"],
  },
  {
    id: "ana-dalzotto",
    firstName: "Ana",
    lastName: "Dalzotto",
    gender: "Female",
    city: "São Paulo",
    state: "SP",
    country: "Brazil",
    phone: "+55 (11) 97654-2233",
    email: "ana.dalzotto@email.com",
    linkedin: "linkedin.com/in/anadalzotto",
    appliedJob: "Social Media & Content Coordinator",
    currentPosition: "Media Specialist",
    source: "LinkedIn",
    createdBy: "Bryan Santana",
    languages: ["Portuguese", "English"],
    pastPositions: ["Media Specialist", "Lead Generation"],
    keywords: ["Media Buying", "Leadhub"],
    createdDate: "2026-07-05",
    photoUrl: "https://placehold.co/150x150/eab308/ffffff?text=AD",
    resumeUrl: null,
    tags: ["Active Search", "Top Fit"],
    preferredContract: "Full-time",
    workModel: "Remote",
    salaryExpectation: "R$ 4.800 / month",
    skills: ["Media Buying", "Lead Generation", "Meta Ads"],
  },
  {
    id: "isabella-monteiro",
    firstName: "Isabella",
    lastName: "Monteiro",
    gender: "Female",
    city: "Curitiba",
    state: "Paraná",
    country: "Brazil",
    phone: "+55 41 99876-5432",
    email: "isabella.silva@email.com",
    linkedin: "linkedin.com/in/isabellasilva-hr",
    appliedJob: "Social Media & Content Coordinator",
    currentPosition: "Social Media Analyst",
    source: "LinkedIn",
    createdBy: "Rafael Sousa",
    languages: ["Portuguese", "English", "Spanish"],
    pastPositions: ["Social Media - Analista Pleno", "BRW Group"],
    keywords: ["Recruitment", "HR Tech"],
    createdDate: "2024-05-15",
    photoUrl: "https://placehold.co/150x150/b45309/ffffff?text=IM",
    resumeUrl: null,
    tags: ["Applied", "LinkedIn", "Active Search", "Top Fit", "Follow Up"],
    preferredContract: "Full-time",
    workModel: "Hybrid (2 days in-office)",
    salaryExpectation: "R$ 12.000,00 per Month",
    skills: [
      "Project Management",
      "Agile (Scrum)",
      "Talent Acquisition",
      "Recruitment",
      "HR Tech",
      "Portuguese",
      "English",
    ],
  },
  {
    id: "lucas-garay",
    firstName: "Lucas",
    lastName: "Garay",
    gender: "Male",
    city: "Curitiba",
    state: "PR",
    country: "Brazil",
    phone: "+55 (41) 98123-4455",
    email: "lucas.garay@email.com",
    linkedin: "linkedin.com/in/lucasgaray",
    appliedJob: "Social Media & Content Coordinator",
    currentPosition: "Community Manager",
    source: "CareerPlug",
    createdBy: "Bianca Melo",
    languages: ["Portuguese"],
    pastPositions: ["Community Manager", "Social Media"],
    keywords: ["Community", "Game Studio"],
    createdDate: "2026-07-08",
    photoUrl: "https://placehold.co/150x150/eab308/ffffff?text=LG",
    resumeUrl: null,
    tags: ["Submitted"],
    preferredContract: "Full-time",
    workModel: "Remote",
    salaryExpectation: "R$ 4.500 / month",
    skills: ["Community Management", "Content Calendar"],
  },
  {
    id: "regeane-aparecida",
    firstName: "Regeane",
    lastName: "Aparecida",
    gender: "Female",
    city: "São Paulo",
    state: "SP",
    country: "Brazil",
    phone: "+55 (11) 96543-2211",
    email: "regeane.a@email.com",
    linkedin: "linkedin.com/in/regeaneaparecida",
    appliedJob: "Social Media & Content Coordinator",
    currentPosition: "Video Script Writer",
    source: "ZipRecruiter",
    createdBy: "Bryan Santana",
    languages: ["Portuguese", "English"],
    pastPositions: ["Video Script Writer", "Social Media"],
    keywords: ["Video", "Copywriting"],
    createdDate: "2026-07-12",
    photoUrl: "https://placehold.co/150x150/c2410c/ffffff?text=RA",
    resumeUrl: null,
    tags: ["Client Interview"],
    preferredContract: "Full-time",
    workModel: "Hybrid (2 days in-office)",
    salaryExpectation: "R$ 5.000 / month",
    skills: ["Video Scripting", "Copywriting", "Editing"],
  },
  {
    id: "ana-luiza-ferreira",
    firstName: "Ana Luiza",
    lastName: "Ferreira",
    gender: "Female",
    city: "Belo Horizonte",
    state: "MG",
    country: "Brazil",
    phone: "+55 (31) 95432-1100",
    email: "analuiza.ferreira@email.com",
    linkedin: "linkedin.com/in/analuizaferreira",
    appliedJob: "Social Media & Content Coordinator",
    currentPosition: "Marketing Analyst",
    source: "LinkedIn",
    createdBy: "Rafael Sousa",
    languages: ["Portuguese", "English"],
    pastPositions: ["Media Marketing Analyst"],
    keywords: ["Marketing Analytics"],
    createdDate: "2026-07-14",
    photoUrl: "https://placehold.co/150x150/c2410c/ffffff?text=AF",
    resumeUrl: null,
    tags: ["Client Interview", "Top Fit"],
    preferredContract: "Full-time",
    workModel: "Remote",
    salaryExpectation: "R$ 5.300 / month",
    skills: ["Marketing Analytics", "Reporting", "Campaign Strategy"],
  },
  {
    id: "gabriela-martins",
    firstName: "Gabriela",
    lastName: "Martins",
    gender: "Female",
    city: "Curitiba",
    state: "PR",
    country: "Brazil",
    phone: "+55 (41) 94321-0099",
    email: "gabriela.martins@email.com",
    linkedin: "linkedin.com/in/gabrielamartins",
    appliedJob: "Social Media & Content Coordinator",
    currentPosition: "Content Marketing Specialist",
    source: "Company Website",
    createdBy: "Bianca Melo",
    languages: ["Portuguese"],
    pastPositions: ["Marketing & Content"],
    keywords: ["Content Strategy"],
    createdDate: "2026-07-15",
    photoUrl: "https://placehold.co/150x150/7c3aed/ffffff?text=GM",
    resumeUrl: null,
    tags: ["Offered"],
    preferredContract: "Full-time",
    workModel: "Hybrid (2 days in-office)",
    salaryExpectation: "R$ 5.500 / month",
    skills: ["Content Strategy", "Branding"],
  },
  {
    id: "rafael-souza",
    firstName: "Rafael",
    lastName: "Souza",
    gender: "Male",
    city: "Curitiba",
    state: "PR",
    country: "Brazil",
    phone: "+55 (41) 93210-9988",
    email: "rafael.souza@email.com",
    linkedin: "linkedin.com/in/rafaelsouza",
    appliedJob: "Social Media & Content Coordinator",
    currentPosition: "Content Creator",
    source: "CareerPlug",
    createdBy: "Bryan Santana",
    languages: ["Portuguese"],
    pastPositions: ["Content Creator"],
    keywords: ["Content"],
    createdDate: "2026-07-16",
    photoUrl: "https://placehold.co/150x150/64748b/ffffff?text=RS",
    resumeUrl: null,
    tags: ["Dropped"],
    preferredContract: "Part-time",
    workModel: "Remote",
    salaryExpectation: "R$ 3.500 / month",
    skills: ["Content Creation", "Editing"],
  },
  {
    id: "paulo-roberto-s",
    firstName: "Paulo",
    lastName: "Roberto S.",
    gender: "Male",
    city: "São Paulo",
    state: "SP",
    country: "Brazil",
    phone: "+55 (11) 92109-8877",
    email: "paulo.roberto@email.com",
    linkedin: "linkedin.com/in/paulorobertos",
    appliedJob: "Social Media & Content Coordinator",
    currentPosition: "Senior Video Editor",
    source: "LinkedIn",
    createdBy: "Rafael Sousa",
    languages: ["Portuguese", "English"],
    pastPositions: ["Senior Video Editor"],
    keywords: ["Video Editing"],
    createdDate: "2026-07-13",
    photoUrl: "https://placehold.co/150x150/7c3aed/ffffff?text=PR",
    resumeUrl: null,
    tags: ["Client Interview"],
    preferredContract: "Full-time",
    workModel: "Remote",
    salaryExpectation: "R$ 6.200 / month",
    skills: ["Video Editing", "Motion Graphics", "Premiere Pro"],
  },
  {
    id: "cyndhara-galdino",
    firstName: "Cyndhara",
    lastName: "Galdino",
    gender: "Female",
    city: "Curitiba",
    state: "PR",
    country: "Brazil",
    phone: "+55 (41) 91098-7766",
    email: "cyndhara.galdino@email.com",
    linkedin: "linkedin.com/in/cyndharagaldino",
    appliedJob: "Social Media & Content Coordinator",
    currentPosition: "Freelance Videomaker",
    source: "ZipRecruiter",
    createdBy: "Bianca Melo",
    languages: ["Portuguese"],
    pastPositions: ["Videomaker", "Social Media", "Freelance Professional"],
    keywords: ["Videomaker", "Freelance"],
    createdDate: "2026-07-11",
    photoUrl: "https://placehold.co/150x150/eab308/ffffff?text=CG",
    resumeUrl: null,
    tags: ["Client Interview", "Top Fit"],
    preferredContract: "Freelance",
    workModel: "Remote",
    salaryExpectation: "R$ 4.000 / month",
    skills: ["Video Production", "Editing", "Social Media"],
  },
];